# Generated by Django 5.0.1 on 2024-01-25 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0003_delete_endpoint"),
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="app",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="applications.application",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="app",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="applications.application",
            ),
            preserve_default=False,
        ),
    ]
