# Generated by Django 5.0.1 on 2024-01-26 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_category_app_product_app"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
