# Generated by Django 5.0.1 on 2024-01-28 11:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_alter_product_rating"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
