# Generated by Django 5.0.1 on 2024-01-28 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["-id"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-id"]},
        ),
    ]
