# Generated by Django 5.0.1 on 2024-01-25 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0002_endpoint"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Endpoint",
        ),
    ]
